name: ai-smcg-env
channels:
  - conda-forge
  - defaults
  - pytorch # PyTorch channel
  - sfe1ed40
dependencies:
  - python
  - langchain
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly # Use this for CPU-only installation; replace with cudatoolkit=11.1 for GPU support
  - pip
  - pip:
    # - python-dotenv
    # - micrograd
    # - graphviz

# Use conda depdencies above where possible. This is because:
# - Dependency resolution handled more robustly especially for non-python dependencies. Pip focuses on Python packages
# - Conda packages built specifically for certain environments
# - Conda installs pre-compiled binaries, which can be faster